### ISSUE TITLE
Missing release on npm

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bundler#16] opened 2022-01-17 17:41 UTC
#### Reason/Context
Seems like there are no releases yet, is that on purpose or? 🤔

**Comment by derberg** [comment] 2022-01-17 19:50
@Souvikns is checking if some final fixes need to be done before we publish, this is why it is not there yet

**Comment by derberg** [comment] 2022-01-18 12:40
closing as it is not a bug, we just did not release it yet

**Closed by derberg** 2022-01-18 12:40 UTC
Labels: bug
